changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🚀 New Features"
      labels:
        - feature
        - enhancement
    - title: "🔌 New Adapters"
      labels:
        - adapter
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📦 Dependencies"
      labels:
        - dependencies
    - title: "🔧 Maintenance"
      labels:
        - chore
        - maintenance
        - ci
