{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hivepulse.fullname" . }}
  labels:
    {{- include "hivepulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  HIVEPULSE_DB_URL: {{ include "hivepulse.databaseUrl" . | quote }}
  HIVEPULSE_JWT_SECRET: {{ .Values.env.jwtSecret | quote }}
  HIVEPULSE_JWT_REFRESH_SECRET: {{ .Values.env.jwtRefreshSecret | quote }}
  HIVEPULSE_ENCRYPTION_KEY: {{ .Values.env.encryptionKey | quote }}
  HIVEPULSE_CORS_ORIGINS: {{ .Values.env.corsOrigins | quote }}
  HIVEPULSE_PORT: {{ .Values.env.apiPort | quote }}
  HIVEPULSE_LOG_LEVEL: {{ .Values.env.logLevel | quote }}
{{- end }}
