// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CheckerService is an autogenerated mock type for the CheckerService type
type CheckerService struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, m
func (_m *CheckerService) Check(ctx context.Context, m *domain.Monitor) (*domain.Heartbeat, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *domain.Heartbeat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Monitor) (*domain.Heartbeat, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Monitor) *domain.Heartbeat); ok {
		r0 = rf(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Heartbeat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Monitor) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCheckerService creates a new instance of CheckerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckerService {
	mock := &CheckerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
