// Copyright (C) 2024 Beedevz. Licensed under AGPL v3 — see LICENSE for details.
// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CheckRunner is an autogenerated mock type for the CheckRunner type
type CheckRunner struct {
	mock.Mock
}

// RunCheck provides a mock function with given fields: ctx, monitorID
func (_m *CheckRunner) RunCheck(ctx context.Context, monitorID string) {
	_m.Called(ctx, monitorID)
}

// NewCheckRunner creates a new instance of CheckRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckRunner {
	mock := &CheckRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
