// Copyright (C) 2024 Beedevz. Licensed under AGPL v3 — see LICENSE for details.
// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HeartbeatRepository is an autogenerated mock type for the HeartbeatRepository type
type HeartbeatRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, h
func (_m *HeartbeatRepository) Create(ctx context.Context, h *domain.Heartbeat) error {
	ret := _m.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Heartbeat) error); ok {
		r0 = rf(ctx, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindLatest provides a mock function with given fields: ctx, monitorID, limit
func (_m *HeartbeatRepository) FindLatest(ctx context.Context, monitorID string, limit int) ([]*domain.Heartbeat, error) {
	ret := _m.Called(ctx, monitorID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindLatest")
	}

	var r0 []*domain.Heartbeat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*domain.Heartbeat, error)); ok {
		return rf(ctx, monitorID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*domain.Heartbeat); ok {
		r0 = rf(ctx, monitorID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Heartbeat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, monitorID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUptime provides a mock function with given fields: ctx, monitorID, since
func (_m *HeartbeatRepository) GetUptime(ctx context.Context, monitorID string, since time.Time) (int64, int64, error) {
	ret := _m.Called(ctx, monitorID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetUptime")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (int64, int64, error)); ok {
		return rf(ctx, monitorID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) int64); ok {
		r0 = rf(ctx, monitorID, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) int64); ok {
		r1 = rf(ctx, monitorID, since)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time) error); ok {
		r2 = rf(ctx, monitorID, since)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewHeartbeatRepository creates a new instance of HeartbeatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeartbeatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HeartbeatRepository {
	mock := &HeartbeatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
