// Copyright (C) 2024 Beedevz. Licensed under AGPL v3 — see LICENSE for details.
// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IncidentRepository is an autogenerated mock type for the IncidentRepository type
type IncidentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, incident
func (_m *IncidentRepository) Create(ctx context.Context, incident *domain.Incident) error {
	ret := _m.Called(ctx, incident)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Incident) error); ok {
		r0 = rf(ctx, incident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActive provides a mock function with given fields: ctx, q, offset, limit
func (_m *IncidentRepository) FindActive(ctx context.Context, q string, offset int, limit int) ([]*domain.Incident, int, error) {
	ret := _m.Called(ctx, q, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindActive")
	}

	var r0 []*domain.Incident
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Incident, int, error)); ok {
		return rf(ctx, q, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Incident); ok {
		r0 = rf(ctx, q, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, q, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, q, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByMonitorAndTimeRange provides a mock function with given fields: ctx, monitorID, since
func (_m *IncidentRepository) FindByMonitorAndTimeRange(ctx context.Context, monitorID string, since time.Time) ([]*domain.Incident, error) {
	ret := _m.Called(ctx, monitorID, since)

	if len(ret) == 0 {
		panic("no return value specified for FindByMonitorAndTimeRange")
	}

	var r0 []*domain.Incident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.Incident, error)); ok {
		return rf(ctx, monitorID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.Incident); ok {
		r0 = rf(ctx, monitorID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, monitorID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindRecent provides a mock function with given fields: ctx, q, offset, limit
func (_m *IncidentRepository) FindRecent(ctx context.Context, q string, offset int, limit int) ([]*domain.Incident, int, error) {
	ret := _m.Called(ctx, q, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecent")
	}

	var r0 []*domain.Incident
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Incident, int, error)); ok {
		return rf(ctx, q, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Incident); ok {
		r0 = rf(ctx, q, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, q, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, q, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindResolved provides a mock function with given fields: ctx, q, offset, limit
func (_m *IncidentRepository) FindResolved(ctx context.Context, q string, offset int, limit int) ([]*domain.Incident, int, error) {
	ret := _m.Called(ctx, q, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindResolved")
	}

	var r0 []*domain.Incident
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Incident, int, error)); ok {
		return rf(ctx, q, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Incident); ok {
		r0 = rf(ctx, q, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, q, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, q, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Resolve provides a mock function with given fields: ctx, monitorID, resolvedAt
func (_m *IncidentRepository) Resolve(ctx context.Context, monitorID string, resolvedAt time.Time) error {
	ret := _m.Called(ctx, monitorID, resolvedAt)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, monitorID, resolvedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIncidentRepository creates a new instance of IncidentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIncidentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IncidentRepository {
	mock := &IncidentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
