// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/beedevz/hivepulse/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// SchedulerService is an autogenerated mock type for the SchedulerService type
type SchedulerService struct {
	mock.Mock
}

// Add provides a mock function with given fields: m
func (_m *SchedulerService) Add(m *domain.Monitor) {
	_m.Called(m)
}

// Remove provides a mock function with given fields: monitorID
func (_m *SchedulerService) Remove(monitorID string) {
	_m.Called(monitorID)
}

// Update provides a mock function with given fields: m
func (_m *SchedulerService) Update(m *domain.Monitor) {
	_m.Called(m)
}

// NewSchedulerService creates a new instance of SchedulerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerService {
	mock := &SchedulerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
