// Copyright (C) 2024 Beedevz. Licensed under AGPL v3 — see LICENSE for details.
// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WSBroadcaster is an autogenerated mock type for the WSBroadcaster type
type WSBroadcaster struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: data
func (_m *WSBroadcaster) Broadcast(data []byte) {
	_m.Called(data)
}

// NewWSBroadcaster creates a new instance of WSBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWSBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *WSBroadcaster {
	mock := &WSBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
